apiVersion: v1
kind: PersistentVolume
metadata:
  name: grupob3-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  storageClassName: manual
  hostPath:
    path: /mnt/data/grupob3

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: grupob3-pvc
  namespace: grupob3
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: manual
  resources:
    requests:
      storage: 1Gi